spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.vinay.urlshortener: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"


